#!/bin/bash

mkdir valgrind
cd valgrind

wget http://valgrind.org/downloads/valgrind-3.11.0.tar.bz2
tar xjf valgrind-3.11.0.tar.bz2

cd valgrind-3.11.0
apt-get install automake libc6-dbg
./autogen.sh
./configure
make
make install

cd ..
rm -rf valgrind

