#!/bin/bash

killall kamailio

echo -e "\e[30;48;5;82m make sip_single_port module \e[0m"
make modules modules=modules/sip_single_port

echo -e "\e[30;48;5;82m copy built module to kamailio libs \e[0m"
cp modules/sip_single_port/sip_single_port.so /usr/local/lib/kamailio/modules/

echo -e "\e[30;48;5;82m reset the screen \e[0m"
reset

# run kamailio from within home directory so the core can be written on seg. fault
cd

# enables creating core on segmentation fault
ulimit -c unlimited

echo -e "\e[30;48;5;82m run kamailio \e[0m"
kamailio


tail -f /var/log/syslog
