#!/bin/bash

if [ "$EUID" -ne 0 ]; then 
	echo "Please run as root"
	exit
fi

if not hash tshark 2>/dev/null; then
	echo "Please install tshark"
	exit
fi

if not hash tcpdump 2>/dev/null; then
        echo "Please install tcpdump"
        exit
fi

THRESHOLD=${1:-50}

echo "Packet loss threshold set to $THRESHOLD"
echo "Press [CTRL+C] to stop..."

RUN=1
local_ip=`ifconfig eth0 | grep inet | awk '{print $2}' | sed 's/addr://' | grep .`

capture_command="tcpdump dst net $local_ip -w dump.pcap &"
rtcp_filter="tshark -r /usr/local/src/dump.pcap -R 'rtcp.ssrc.cum_nr > $THRESHOLD' | wc -l"

while true
do
	if [ $RUN -eq 1 ]
	then
		# wait for the first occurence of RTCP packet which 
		# suits the filter and then exit tshark
		tcpdump dst net $local_ip -w dump.pcap &
#		su - kamailio -c '$capture_command'
		pid=$!
		trap "kill $pid 2> /dev/null" EXIT
		RUN=0
	fi

	rtcp_count=`tshark -r /usr/local/src/dump.pcap -R "rtcp.ssrc.cum_nr > $THRESHOLD" | wc -l`
#	rtcp_count=`su - kamailio -c '$rtcp_filter'`
#	rtcp_count=`tshark -r dump.pcap -R "rtcp.ssrc.cum_nr > $THRESHOLD" | wc -l`
	if [ $rtcp_count > 1 ]
	then
		echo "RTCP count: $rtcp_count"

		# kill the tcpdump
		kill $pid 2> /dev/null
		# notify kamailio about packet loss
		touch notify

		break;
	fi

	sleep 1
done #&

trap - EXIT
